# _config.yml

title: Furniture Style Sleuth API Docs
remote_theme: just-the-docs/just-the-docs
plugins: jekyll-remote-theme


# Base URL if deploying under a subpath
baseurl: "/furniture-style-sleuth-docs"


# Enable the navigation sidebar
just_the_docs:
  logo: "/assets/images/logo.png"  # Optional
  aux_links:
    GitHub Repo: https://github.com/rachaelallen91/furniture-style-sleuth-docs

# Sidebar navigation structure
collections:
  docs:
    output: true
    permalink: /:path/

nav:
  - title: Home
    url: index.md

  - title: Quickstart
    url: quickstart.md

  - title: Tutorials
    children:
      - title: Before You Begin
        url: Tutorials/before-you-begin.md
      - title: Start the Service
        url: Tutorials/start-the-service.md
      - title: Add Furniture
        url: Tutorials/tutorial-add-furniture.md
      - title: Find by Style
        url: Tutorials/tutorial-find-furniture-by-style.md
      - title: Update Style
        url: Tutorials/tutorial-update-style.md

  - title: API Reference
    children:
      - title: Base URL
        url: API Reference/base-url.md
      - title: Furniture Model
        url: API Reference/furniture.md
      - title: Style Model
        url: API Reference/styles.md

  - title: Endpoints
    children:
      - title: GET, POST, PUT, PATCH, DELETE
        url: topic-list.md

  - title: Errors
    url: errors.md


